version: "3.7"
services:
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 7432:5432
  blockscout:
    depends_on:
      - postgres
    # image: blockscout/blockscout:${DOCKER_TAG_BLOCKSCOUT:-latest}
    image: shidaxi/blockscout:${DOCKER_TAG_BLOCKSCOUT:-latest}
    restart: always
    container_name: blockscout
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_VARIANT: ganache
      ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8045/
      ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8045/
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
      DISABLE_KNOWN_TOKENS: 'true'
      DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
      ECTO_USE_SSL: 'false'
      SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
      CHAIN_ID: '1337'
    ports:
      - 4000:4000
  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:${DOCKER_TAG_SMART_CONTRACT_VERIFIER:-latest}
    restart: always
    container_name: smart-contract-verifier
    volumes:
      - ./blockscout/solidity-compilers:/tmp/solidity-compilers:rw
      - ./blockscout/vyper-compilers:/tmp/vyper-compilers:rw
    env_file:
      - ./envs/common-smart-contract-verifier.env
    ports:
      - 8043:8043