version: "3.7"
services:
  foundry-anvil:
    hostname: foundry-anvil
    container_name: foundry-anvil
    image: ghcr.io/foundry-rs/foundry:${DOCKER_TAG_FOUNDRY:-latest}
    entrypoint:
      - sh
      - -c
      - anvil -a 2 -p 8045
    ports:
      - "8045:8045"
    volumes:
      - ./foundry:/root/.ethereum